import { AccountPage } from "@/components/account/account-page";

const posts = [
  { category: "How it works", date: "06 Aug 2026", readTime: "4 min read", title: "How people-powered delivery works", text: "A simple guide to matching parcels with travellers already going your way.", paragraphs: ["A parcel does not always need a dedicated delivery vehicle. Often, someone is already travelling between the two places it needs to reach. Trickle brings those two plans together: a sender describes a parcel and route, while a traveller shares an existing journey and the space they can offer.", "The sender starts by choosing a pickup date and entering the pickup and delivery locations. Clear addresses matter because route matching depends on the places, direction, and timing being accurate. Parcel type, approximate weight, size, and handling notes help a traveller decide whether the request fits their plan.", "Travellers can post a journey with their departure and arrival points, travel dates, mode of travel, maximum weight, parcel count, and accepted parcel types. Senders then compare the route first, followed by the practical details. A matching route is more useful than a promising profile with the wrong timing.", "Once a sender finds a suitable plan, they can request pickup with the parcel details attached. The traveller reviews the request before coordinating the handoff. Both people should keep the agreed location and timing clear, use the app details as their shared reference, and communicate promptly if the journey changes.", "People-powered delivery works best when both sides are precise and considerate. It is not about treating a traveller as an anonymous courier; it is about coordinating a real journey between two people, with enough information for each person to make a confident decision."] },
  { category: "Parcel care", date: "01 Aug 2026", readTime: "4 min read", title: "Planning a smoother parcel handoff", text: "Practical tips for clear pickup details, safe packaging, and reliable communication.", paragraphs: ["A smooth handoff begins before anyone meets. Start with an honest parcel description: what the item is, how fragile it may be, whether it needs a particular orientation, and whether there are any restrictions on how it should be carried. Good notes reduce uncertainty and help travellers accept only requests they can handle responsibly.", "Packaging should match the item rather than simply making the parcel look neat. Use strong outer material, protect corners and surfaces, prevent movement inside the package, and keep the final parcel within the weight and size information shared in the request. If an item needs special treatment, mention it before the traveller agrees.", "Choose a practical pickup point with clear access and enough visibility for both people to identify one another. Confirm the date, approximate time, and contact method in advance. A short message that repeats the parcel description and handoff location can prevent the small misunderstandings that create delays on a busy travel day.", "At pickup, the sender and traveller should confirm that the parcel matches the request. The traveller should not accept a parcel whose contents, weight, packaging, or condition is materially different from what was described. If plans change, tell the other person quickly rather than waiting until the original handoff time has passed.", "Good handoffs are built from ordinary habits: accurate details, safe packaging, a visible meeting place, and timely updates. These habits protect the sender's expectations and give the traveller a clear, manageable responsibility throughout the journey."] },
  { category: "For travellers", date: "27 Jul 2026", readTime: "3 min read", title: "Travel with room for one more thing", text: "What travellers should know before sharing their route and available parcel space.", paragraphs: ["Posting a travel plan is an invitation to compare your route with a parcel that needs to move. The most helpful plan is not necessarily the one with the longest description. It is the one that tells senders where you are travelling, when you are travelling, how you will travel, and what you can realistically carry.", "Be specific about capacity. Maximum weight and parcel count give senders a useful boundary, while accepted parcel types make it easier to avoid requests that do not fit your preferences. It is better to publish a smaller capacity you can reliably manage than to accept more than you can keep secure during a crowded journey.", "Think about handoffs as part of the route. Decide whether you can meet at a station, airport, public landmark, or another accessible place. If your arrival time is uncertain, say so. A sender can make a better decision when they understand the practical timing rather than only seeing the origin and destination.", "Before accepting a request, review the parcel description and ask for clarification when something is unclear. At pickup, compare the actual parcel with the request. If the item, packaging, or weight is materially different, pause the handoff and contact the sender or Trickle support rather than taking on an unexpected risk.", "A thoughtful travel plan creates trust before the first message. Accurate capacity, realistic timing, and clear boundaries help travellers share a route without turning their trip into an improvised delivery operation."] },
  { category: "Safety", date: "20 Jul 2026", readTime: "4 min read", title: "Small habits that make handoffs safer", text: "A practical checklist for thoughtful pickup and delivery conversations.", paragraphs: ["Safety is usually a collection of small decisions rather than one dramatic action. Keep the parcel description, route, date, and handoff expectations visible in the app record. When the conversation moves quickly, those details give both people a stable reference for what was actually agreed.", "Use a visible and appropriate location for the handoff whenever possible. Make sure both people can identify the place and one another without exchanging unnecessary personal information. Do not share an OTP, password, payment credential, or identity document in chat, and do not feel pressured to continue a conversation that makes you uncomfortable.", "At pickup, check the parcel against the description. Senders should not conceal contents, and travellers should not accept an item simply because a meeting has already been arranged. A polite pause is better than a rushed decision when weight, packaging, or contents are unclear.", "If there is a delay, update the other person as soon as you know. If a parcel is lost, damaged, misrepresented, or connected to suspicious behaviour, preserve the relevant messages and contact support. For immediate danger, contact local emergency services first; platform support should not be treated as an emergency service.", "Clear records, sensible meeting places, honest descriptions, and early reporting make the service easier to use safely. These practices also make it easier for support to understand what happened if a handoff does not go as planned."] },
  { category: "Community", date: "12 Jul 2026", readTime: "4 min read", title: "Why existing journeys make useful routes", text: "When a parcel follows an existing trip, a little spare capacity can connect two places more simply.", paragraphs: ["Many delivery requests begin with a simple mismatch: one person needs to send something, while another person is already travelling in the right direction. A separate delivery journey may be expensive or inconvenient, even though the parcel could fit naturally into a trip that is already happening.", "Trickle is designed around that existing movement. A traveller can publish a route, date, travel mode, and available capacity. A sender can search for a route that makes sense, review the travel plan, and decide whether the timing and handoff expectations work for the parcel.", "The model depends on clarity rather than assumptions. A route that looks close on a map may not be practical if the pickup location is far from the traveller's starting point or the delivery timing is too tight. That is why origin, destination, dates, capacity, and handoff preferences all matter when comparing a plan.", "It also depends on respect for the person making the journey. Travellers choose what they are comfortable carrying, and senders need to provide accurate information before making a request. Neither side should feel obliged to accept a change that was not part of the original plan.", "When those expectations are clear, a spare corner of an existing journey can become a useful connection. The result is not a promise that every route will match, but a more human way to discover delivery possibilities that are already present in the journeys people are taking."] },
  { category: "Product updates", date: "04 Jul 2026", readTime: "3 min read", title: "A clearer way to review a travel plan", text: "What to look for when comparing routes, dates, capacity, and accepted parcel types.", paragraphs: ["A travel plan contains several details, and each one answers a different question. The route tells you whether the journey is going in the right direction. The travel dates tell you whether the parcel can reach the destination at the right time. Start with those two details before looking at anything else.", "Next, check the travel mode and the practical handoff points. A train, flight, bus, or car journey can have very different luggage constraints and timing patterns. The best match is one whose pickup and delivery expectations fit the traveller's actual movement, not simply one whose cities appear close together.", "Capacity details make the comparison more concrete. Maximum weight, maximum parcel count, and accepted parcel types show what the traveller expects to carry. Compare these details with the parcel's real condition and packaging. If the parcel is fragile, unusually shaped, or heavier than expected, ask before requesting pickup.", "Finally, look at the date and the plan's overall completeness. A clear plan gives both people fewer unanswered questions. If an important detail is missing, use the request conversation to clarify it early. A short, direct question can prevent a long problem after the journey has begun.", "Reviewing a plan carefully does not need to take long. Route, date, mode, capacity, parcel type, and handoff expectations form a practical checklist. Once those pieces align, both sender and traveller can move forward with a much clearer understanding of the request."] },
];

export default function BlogPage() {
  return (
    <AccountPage eyebrow="Trickle journal" title="Ideas for better journeys" description="Stories, practical guidance, and updates from the people building more useful routes together.">
      <article className="border-t-2 border-[#e85b43] bg-[#183b3a] p-7 text-white sm:p-9">
        <p className="text-xs font-semibold uppercase tracking-[0.16em] text-[#e7b65c]">{posts[0].category} · {posts[0].date}</p>
        <h2 className="mt-4 max-w-2xl text-3xl font-semibold tracking-[-0.04em]">{posts[0].title}</h2>
        <p className="mt-4 max-w-2xl text-base leading-7 text-[#d8e3de]">{posts[0].text}</p>
        <p className="mt-5 max-w-3xl border-t border-[#c5d4ce]/30 pt-5 text-sm leading-7 text-[#c5d4ce]">{posts[0].paragraphs[0]}</p>
        <details className="mt-5 max-w-3xl border-t border-[#c5d4ce]/30 pt-4">
          <summary className="cursor-pointer list-none text-sm font-semibold text-[#e7b65c]">Read full article <span aria-hidden="true">→</span></summary>
          <div className="mt-4 space-y-4 text-sm leading-7 text-[#c5d4ce]">{posts[0].paragraphs.slice(1).map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div>
        </details>
        <span className="mt-6 inline-block text-xs font-semibold uppercase tracking-[0.1em] text-[#c5d4ce]">{posts[0].readTime}</span>
      </article>
      <div className="mt-6 grid gap-5 md:grid-cols-2">
        {posts.slice(1).map((post) => (
          <article key={post.title} className="border-t-2 border-[#e7b65c] bg-[#fbfaf7] p-6">
            <div className="flex flex-wrap items-center justify-between gap-2 text-xs font-semibold uppercase tracking-[0.1em] text-[#e85b43]"><span>{post.category}</span><span className="text-[#62645f]">{post.date}</span></div>
            <h2 className="mt-4 text-xl font-semibold text-[#183b3a]">{post.title}</h2>
            <p className="mt-3 text-sm leading-6 text-[#62645f]">{post.text}</p>
            <p className="mt-4 border-t border-[#ded8ce] pt-4 text-sm leading-6 text-[#62645f]">{post.paragraphs[0]}</p>
            <details className="mt-4 border-t border-[#ded8ce] pt-4">
              <summary className="cursor-pointer list-none text-sm font-semibold text-[#e85b43]">Read full article <span aria-hidden="true">→</span></summary>
              <div className="mt-4 space-y-4 text-sm leading-6 text-[#62645f]">{post.paragraphs.slice(1).map((paragraph) => <p key={paragraph}>{paragraph}</p>)}</div>
            </details>
            <span className="mt-5 inline-block text-xs font-semibold uppercase tracking-[0.1em] text-[#183b3a]">{post.readTime}</span>
          </article>
        ))}
      </div>
    </AccountPage>
  );
}
